# Generated by Django 5.1 on 2024-08-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_newslettersubscription_testimonial'),
        ('orders', '0002_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='producttag',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvisit',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productgallery',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='productvisit',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProductBrand',
        ),
        migrations.DeleteModel(
            name='ProductTag',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductGallery',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='ProductVisit',
        ),
    ]
