# Generated by Django 5.1 on 2024-08-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_whychooseus_whychooseusimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeHelpSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_1_image', models.ImageField(upload_to='we-help-section-images')),
                ('grid_2_image', models.ImageField(upload_to='we-help-section-images')),
                ('grid_3_image', models.ImageField(upload_to='we-help-section-images')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('list_item_1', models.CharField(max_length=100)),
                ('list_item_2', models.CharField(max_length=100)),
                ('list_item_3', models.CharField(max_length=100)),
                ('list_item_4', models.CharField(max_length=100)),
            ],
        ),
    ]
